### ISSUE TITLE
The mod ID included in your request could not be found (cache update).

### ISSUE THREAD

**Issue by Tenome** [trumank/mint#113]
While trying to update my cache, I get this error. The mod.io page is still up, so I know it's not that it was removed.

Code: 403
error_ref: 15024

**Comment by jieyouxu** [comment]
Can you provide a bit more information? What's the mod.io URL? Has the author made the mod hidden or have they renamed the mod?

**Comment by jieyouxu** [comment]
I'm going to close this because there are no further information provided. If you have any more information that you can provide, such as your mod list, then feel free to reopen this issue.

If you are still having this problem, try deleting the cache directory at `%AppData%\Local\drg-mod-integration\cache`.
