### ISSUE TITLE
Regarding the new sorting function, should there be time sorting by adding mods?

### ISSUE THREAD

**Issue by 3qingmi** [trumank/mint#165]
Regarding the new sorting function, should there be a time to add mods for sorting.
I add a lot of mods, but I'm used to managing it by the time I add the mods myself. Because the more newly added a mod is, the more I need to test its functionality and stability. But sometimes using the sorting function of the software will disrupt the order of my mods, and my original order of use can never be restored, which makes it difficult for me to identify which one is my newly added mod.

**Comment by trumank** [comment]
Fixed by 7b6f40fb151bc64a75b973dd4a72a58efc95a3ef which makes sorting only apply to the view and doesn't change the underlying mod order. This means that when sorting is disabled, the underlying order will be visible which will show most recently added mods at the top and allow manually re-ordering like before.

![image](https://github.com/trumank/mint/assets/1144160/b11a5786-d2d4-4f0e-83dc-35cbca8aea1b)
