### ISSUE TITLE
"Failed to write hook to 'C:\Program Files (x86)\Steam\steamapps\common\Deep Rock Galactic\FSD\Binaries\Win64\x3daudio1_7.dll'

### ISSUE THREAD

**Issue by WackoFurball6** [trumank/mint#175]
This is the message that appeared after I tried to install the mods. My antivirus flagged x3daudio1_7.dll as infected with a trojan the first time I tried to install the mods, so I told it to revert it back (which it did) and to ignore both MINT and the .dll file... but it still gives me this error and it can't even uninstall the mods. Turning the antivirus off didn't solve it, neither reinstalling the game or verifying the game's cache. At some point while trying some other things the antivirus still decided to completely remove the x3daudio1_7.dll file... and now I can't seem to get it back, not even after reinstalling the game. So yeah, it's completely messed up :/

**Comment by jieyouxu** [comment]
Unfortunately we can't do anything about your antivirus flagging the hook mint generates (you'll have to ignore the hook, one possibility is to add an exception for the game folder, but I won't make the suggestion to modify antivirus config because that's your decision to make considering the risks).
