### ISSUE TITLE
cant open Mint,help me plz!

### ISSUE THREAD

**Issue by biscuit-7x8** [trumank/mint#241]
when i added mods,my pc suddenly collapsed.
after the restart i cant open the mint anymore.
after this interface pops up it will flash back
![CC75A02705BB3787F82B5B696D117907](https://github.com/user-attachments/assets/ffd0e355-07fc-4585-8a29-76f5d244d23b)

**Comment by AKbeyonder** [comment]
Hey, unfortunately the main authors for this are currently retired. I think I had a similar issue, have you tried deleting cache from here: AppData\Local\drg-mod-integration\cache ? Make sure to back up just in case. 
Otherwise you could try joining and asking around in the Practical DRG discord server.

**Comment by biscuit-7x8** [comment]
> Hey, unfortunately the main authors for this are currently retired. I think I had a similar issue, have you tried deleting cache from here: AppData\Local\drg-mod-integration\cache ? Make sure to back up just in case. Otherwise you could try joining and asking around in the Practical DRG discord server.

Thanks for your help!
it really worked when i deleted them.

**Comment by biscuit-7x8** [comment]
I deleted two folders from: AppData\Roaming\drg-mod-integration
and here: AppData\Local\drg-mod-integration
