### ISSUE TITLE
AssetRegistry.bin population/merging

### ISSUE THREAD

**Issue by trumank** [trumank/mint#57]
Asset registry files are stripped from mods since they are rarely used to access mods assets, however the official integration does attempt (it's very broken) to populate the game's asset registry with mod asset registries upon mounting. There are two ways this could be done:

Split mod registries with the game's registry as-is
  - many mods don't include the asset registry
  - many mods include asset registries with invalid entries

Parse mod asset contents to determine asset information to more accurately populate registry information
  - depends on being able to accurately parse assets
  - could be slow so would likely require caching mod metadata

**Comment by trumank** [comment]
Fixed by 9998be3 which rebuilds the base game's `AssetRegistry.bin` to contain new entries obtained from parsing all mod asset headers.

**Comment by PrincessRTFM** [comment]
Sorry to tap a closed issue, but does this mean that the [wiki-listed "lack of Asset Registry support (unimplemented in mint)" causing mod conflicts](https://github.com/trumank/mint/wiki/Frequently-Asked-Questions#why-does-mod-xxx-not-work) _has_ been fixed? If so, the wiki should probably be updated to reflect this, as there are at least two places where it currently says otherwise.
